apiVersion: v1
kind: Service
metadata:
  name: file-manager-prod-service
  labels:
    app: file-manager-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.109
  externalIPs:
  - 10.24.24.109
  ports:
  - name: http
    port: 81 #local out port
    protocol: TCP
    targetPort: 81 # container port
  selector:
    app: file-manager-prod #find all pod with app name
  sessionAffinity: None
